// POST /api/admin — gallery administration (admin.stones.art).
// Auth: x-admin-pass header checked against env ADMIN_PASSWORD.
//
// Stone rows live in Supabase; image bytes (originals, looks, cutouts) live in
// Cloudflare R2 (bucket "shay-stones") served from cdn.shaym.beauty.
//
// A stone has 1+ source photos; the admin marks one as primary (the "original",
// shown in the gallery + info popup); the rest are extra angles fed to look
// generation. The analyze stage plans a VARIABLE set of "looks" (no fixed count
// per category — whatever flatters the stone, total ≤ MAX_LOOKS), each then
// generated by a separate `look` call to stay under the 60s function budget.
//
// Actions:
//   ping
//   list                                                   → { stones:[...] }
//   offers                                                 → { offers:[...] }
//   create  {name?, width_cm?, depth_cm?, photos:[b64 1-8], primary?} → {id, photos, ...}
//   analyze {id}                                           → {name, height_cm, looks}
//   look    {id, index}                                    → {index, kind, url}
//   cutout  {id}                                           → {cutout}
//   update  {id, name?, width_cm?, height_cm?, depth_cm?}  → {ok}
//   finalize{id}                                           → {ok, id}

const TEXT_MODEL = "gemini-2.5-flash";
const IMAGE_MODEL = "gemini-3.1-flash-image";
const API = "https://generativelanguage.googleapis.com/v1beta/models";
const KINDS = ["blur", "outdoor", "indoor", "creative"];
const LABEL = { blur: "Sophisticated Blur", outdoor: "Outdoor", indoor: "Indoor", creative: "Creative" };
const MAX_LOOKS = 12;
const MAX_PHOTOS = 8;

const { r2put, r2del, CDN } = require("./_storage.js");
const budget = require("./_budget.js");
const auth = require("./_auth.js");

const slug = (s) => String(s).trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const num = (d) => (Number(d) > 0 && Number(d) < 10000 ? Number(d) : null);

const sb = () => ({
  url: process.env.SUPABASE_URL,
  headers: {
    apikey: process.env.SUPABASE_SERVICE_KEY,
    Authorization: `Bearer ${process.env.SUPABASE_SERVICE_KEY}`,
  },
});

async function row(id) {
  const { url, headers } = sb();
  const r = await fetch(`${url}/rest/v1/stones?id=eq.${encodeURIComponent(id)}&select=*`, { headers });
  return r.ok ? (await r.json())[0] : null;
}

async function patch(id, fields) {
  const { url, headers } = sb();
  const r = await fetch(`${url}/rest/v1/stones?id=eq.${encodeURIComponent(id)}`, {
    method: "PATCH",
    headers: { ...headers, "Content-Type": "application/json", Prefer: "return=minimal" },
    body: JSON.stringify(fields),
  });
  if (!r.ok) throw new Error(`db patch: ${r.status} ${(await r.text()).slice(0, 200)}`);
}

async function upload(path, buf) {
  return r2put(path, buf, "image/jpeg");
}

async function gemini(model, parts, { imageOut = false } = {}) {
  for (let attempt = 1; ; attempt++) {
    const r = await fetch(`${API}/${model}:generateContent?key=${process.env.GEMINI_AI_STUDIO}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [{ parts }],
        ...(imageOut ? { generationConfig: { responseModalities: ["IMAGE"], imageConfig: { imageSize: "2K" } } } : {}),
      }),
    });
    if ((r.status === 429 || r.status >= 500) && attempt <= 2) {
      await new Promise((ok) => setTimeout(ok, attempt * 3000));
      continue;
    }
    if (!r.ok) throw new Error(`${model}: HTTP ${r.status}`);
    const data = await r.json();
    const out = data.candidates?.[0]?.content?.parts ?? [];
    if (imageOut) {
      const img = out.find((p) => p.inlineData);
      if (img) return Buffer.from(img.inlineData.data, "base64");
      if (attempt <= 2) continue;
      throw new Error(`${model}: no image`);
    }
    const text = out.filter((p) => p.text).map((p) => p.text).join("");
    if (text) return text;
    if (attempt <= 2) continue;
    throw new Error(`${model}: no text`);
  }
}

function parseJson(text, stage) {
  const m = text.match(/```json\s*([\s\S]*?)```/) ?? text.match(/```\s*([\s\S]*?)```/);
  try { return JSON.parse(m ? m[1] : text); }
  catch { throw new Error(`${stage}: bad JSON from model`); }
}

const imagePart = (buf) => ({ inlineData: { mimeType: "image/jpeg", data: buf.toString("base64") } });

// All source photos for a stone: primary (original) first, then angle photos.
function originalUrls(stoneRow) {
  const img = stoneRow.images || {};
  const urls = [img.original];
  for (let i = 2; i <= MAX_PHOTOS; i++) if (img["original_" + i]) urls.push(img["original_" + i]);
  return urls.filter(Boolean);
}
async function fetchBuf(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error("could not fetch image");
  return Buffer.from(await r.arrayBuffer());
}
async function fetchOriginals(stoneRow) {
  const urls = originalUrls(stoneRow);
  if (!urls.length) throw new Error("stone has no original image");
  return Promise.all(urls.map(fetchBuf));
}
async function fetchOriginal(stoneRow) {
  return (await fetchOriginals(stoneRow))[0];
}

// ---- pipeline stages --------------------------------------------------------

async function stageAnalyze(stoneRow) {
  const bufs = await fetchOriginals(stoneRow);
  const imgs = bufs.map(imagePart);

  const analysisPrompt = `Analyze the stone shown in ${bufs.length === 1 ? "this photo" : `these ${bufs.length} photos (different angles of the SAME stone)`}.
Also estimate the stone's real-world HEIGHT in centimeters — the vertical extent of the physical stone as it sits. Use whatever scale cues are visible (a hand or fingers, ground texture, nearby objects, depth of field, framing). If no reliable cue exists, give your single best estimate for a stone of this apparent type and framing. Return ONE number, never a range.
Return ONLY JSON:
{
  "name": "a poetic two-word display name for this stone",
  "colors": ["..."],
  "texture": "...",
  "character": "the stone's personality/mood in one sentence",
  "distinctive_features": ["..."],
  "height_cm": <number — your single best estimate of the stone's height in centimeters>,
  "height_reasoning": "one short sentence: which scale cue you used"
}`;
  const analysis = parseJson(await gemini(TEXT_MODEL, [...imgs, { text: analysisPrompt }]), "analysis");

  // Plan a VARIABLE set of looks — no fixed count per category, whatever fits.
  const planPrompt = `You are art-directing a set of re-photographed "looks" of THIS exact stone for a gallery. ${bufs.length} source photo(s) from different angles are provided.

Stone analysis:
${JSON.stringify(analysis, null, 2)}

Decide how many looks of each category genuinely flatter THIS stone — there is NO fixed rule, choose whatever fits its colors, texture, character, and the angles available. Categories:
- "blur": the stone tack-sharp against a sophisticated, softly-blurred background (fine-art product photography, elegant bokeh). Usually 1.
- "outdoor": natural outdoor settings.
- "indoor": interior settings.
- "creative": unexpected, artistic, imaginative, surreal-allowed settings.

Total looks between 5 and ${MAX_LOOKS}. Favour categories that suit this stone; it's fine to give one category several looks and another none. Where multiple angles are provided, use them so different looks reveal different sides.

For each look write a polished image-generation prompt that:
1. Begins with: "Take the exact stone — together with the display stand or mount it is fixed to, if any — from the provided photo(s), preserving its shape, texture, colors, its stand, and every distinctive feature faithfully —"
2. Then describes placement, setting, lighting, camera/lens feel, and mood in rich detail. If the stone has a display stand/mount, it stays on that stand as one piece; never reproduce the original table or surface the stand was photographed on — give it a fresh setting.
3. For "blur": the background must be sophisticatedly blurred (shallow depth of field, refined bokeh), stone in crisp focus.
Also write a short poetic caption (under 12 words) per look.

Return ONLY JSON: { "looks": [ { "kind": "blur|outdoor|indoor|creative", "prompt": "...", "caption": "..." }, ... ] }`;
  const plan = parseJson(await gemini(TEXT_MODEL, [{ text: planPrompt }]), "plan");
  let looks = Array.isArray(plan.looks) ? plan.looks.filter((l) => l && KINDS.includes(l.kind) && l.prompt) : [];
  if (!looks.length) throw new Error("plan: model returned no looks");
  looks = looks.slice(0, MAX_LOOKS);

  const fields = { meta: { analysis, looksPlan: looks } };
  if (!stoneRow.name || stoneRow.name === stoneRow.id) fields.name = analysis.name;
  if (!stoneRow.character) fields.character = analysis.character;
  const estH = Number(analysis.height_cm);
  if (estH > 0 && estH < 10000) { fields.height_cm = estH; fields.dimensions_approx = true; }
  await patch(stoneRow.id, fields);
  return { name: fields.name || stoneRow.name, character: analysis.character, height_cm: fields.height_cm ?? null, looks: looks.length };
}

const COMPOSITION_RULE =
  " Composition requirement: the stone is perfectly centered in the frame, both horizontally and vertically — it is the clear central subject of the image.";

// Generate one planned look (by index) and store it into images.looks[index].
async function stageLook(stoneRow, index) {
  const plan = stoneRow.meta?.looksPlan;
  if (!Array.isArray(plan) || !plan[index]) throw new Error("run analyze first (or bad look index)");
  const look = plan[index];
  const bufs = await fetchOriginals(stoneRow);
  const refs = bufs.slice(0, 3).map(imagePart); // primary + up to 2 angles
  const img = await gemini(IMAGE_MODEL, [...refs, { text: look.prompt + COMPOSITION_RULE }], { imageOut: true });
  const url = await upload(`${stoneRow.id}/look-${index}.jpg`, img);
  const cur = await row(stoneRow.id); // re-read to append safely
  const looks = Array.isArray(cur.images?.looks) ? cur.images.looks.slice() : [];
  looks[index] = { kind: look.kind, src: url, caption: look.caption || "", name: LABEL[look.kind] || look.kind };
  await patch(stoneRow.id, { images: { ...(cur.images || {}), looks } });
  return { index, kind: look.kind, url };
}

// Transparent cutout for the viewer's 3D stone layer.
async function stageCutout(stoneRow) {
  const sharp = require("sharp");
  const buf = await fetchOriginal(stoneRow);
  const prompt = `Isolate the stone — together with the display stand or mount it is physically fixed to — from this photo. Render the EXACT same stone AND its stand — identical shape, texture, colors, lighting and angle — floating on a completely uniform pure green background (#00FF00). KEEP the stand, base or mount that the stone is attached to or seated in: it is part of the piece. REMOVE everything the stand itself rests on — the table, ground, floor, shelf or any surface beneath it — and every other element (no shadow, no soil, no leaves, no pebbles). If the stone has NO stand, output only the stone. The stone-and-stand must be surrounded on ALL sides (including below the bottom of the stand) by flat chroma green. Do not alter the stone or its stand in any way.`;
  const green = await gemini(IMAGE_MODEL, [imagePart(buf), { text: prompt }], { imageOut: true });
  const { data: px, info } = await sharp(green).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  for (let i = 0; i < px.length; i += 4) {
    const [R, G, B] = [px[i], px[i + 1], px[i + 2]];
    if (G > 110 && G > R * 1.45 && G > B * 1.45) px[i + 3] = 0;
    else if (G > 90 && G > R * 1.2 && G > B * 1.2) px[i + 3] = Math.round(255 * 0.35);
  }
  const cutout = await sharp(px, { raw: { width: info.width, height: info.height, channels: 4 } })
    .trim({ threshold: 10 })
    .resize(1024, 1024, { fit: "inside", withoutEnlargement: true })
    .png()
    .toBuffer();
  const publicUrl = await r2put(`cutouts/${stoneRow.id}.png`, cutout, "image/png");
  await patch(stoneRow.id, { images: { ...(stoneRow.images || {}), cutout: publicUrl } });
  return { cutout: publicUrl };
}

// ---- handler ----------------------------------------------------------------

module.exports = async (req, res) => {
  if (req.method !== "POST") { res.statusCode = 405; return res.json({ error: "POST only" }); }
  if (!process.env.ADMIN_PASSWORD) { res.statusCode = 500; return res.json({ error: "Admin is not configured." }); }

  const { action } = req.body || {};
  try {
    // ---- login: password (+ TOTP code if 2FA is enrolled) → signed session ----
    if (action === "login") {
      if (!auth.passwordOk(req.body.password)) { res.statusCode = 401; return res.json({ error: "Wrong password." }); }
      const cfg = await auth.loadAuthConfig();
      if (auth.isEnrolled(cfg)) {
        if (!req.body.code) { res.statusCode = 401; return res.json({ error: "Enter your authenticator code.", need2fa: true }); }
        const { ok } = await auth.verifySecondFactor(cfg, req.body.code);
        if (!ok) { res.statusCode = 401; return res.json({ error: "That code didn't match — try again.", need2fa: true }); }
      }
      return res.json({ token: auth.createSession(), enrolled: auth.isEnrolled(cfg) });
    }

    // ---- every other action requires a valid session token (x-admin-token) ----
    if (!auth.requireSession(req)) { res.statusCode = 401; return res.json({ error: "Please sign in again.", reauth: true }); }

    if (action === "ping") return res.json({ ok: true });

    // ---- 2FA management ----
    if (action === "authStatus") {
      const cfg = await auth.loadAuthConfig();
      return res.json({ enrolled: auth.isEnrolled(cfg), recoveryRemaining: (cfg.recoveryHashes || []).length });
    }
    if (action === "enrollStart") {
      const secret = auth.newSecret();
      const otpauth = auth.otpauthUri(secret);
      const qr = await require("qrcode").toDataURL(otpauth, { margin: 1, width: 220 }).catch(() => null);
      return res.json({ secret, otpauth, qr });
    }
    if (action === "enrollConfirm") {
      if (!auth.totpOk(req.body.secret, req.body.code)) { res.statusCode = 400; return res.json({ error: "Code didn't verify — check your phone's clock and retry." }); }
      const recoveryCodes = auth.newRecoveryCodes(10);
      await auth.saveAuthConfig({ secret: req.body.secret, recoveryHashes: recoveryCodes.map(auth.hashCode), enrolledAt: new Date().toISOString() });
      return res.json({ ok: true, recoveryCodes });
    }
    if (action === "disable2fa") {
      const cfg = await auth.loadAuthConfig();
      if (auth.isEnrolled(cfg)) {
        const { ok } = await auth.verifySecondFactor(cfg, req.body.code);
        if (!ok) { res.statusCode = 400; return res.json({ error: "Enter a current code to turn 2FA off." }); }
      }
      await auth.saveAuthConfig({ secret: null, recoveryHashes: [], enrolledAt: null });
      return res.json({ ok: true });
    }

    // ---- gallery list (admin) ----
    if (action === "list") {
      const { url, headers } = sb();
      const r = await fetch(`${url}/rest/v1/stones?select=id,name,width_cm,height_cm,depth_cm,dimensions_approx,status,images,created_at&order=created_at.desc`, { headers });
      if (!r.ok) throw new Error(`db list: ${r.status}`);
      const rows = await r.json();
      const stones = rows.map((s) => {
        const img = s.images || {};
        const looks = Array.isArray(img.looks) ? img.looks.filter((l) => l && l.src) : [];
        const hero = img.original || looks[0]?.src || null;
        return {
          id: s.id, name: s.name, status: s.status,
          width_cm: s.width_cm, height_cm: s.height_cm, depth_cm: s.depth_cm, dimensions_approx: s.dimensions_approx,
          hero, looks: looks.length || KINDS.filter((k) => img[k]).length, created_at: s.created_at,
        };
      });
      return res.json({ stones });
    }

    // ---- offers list (admin), newest first, with stone name + original ----
    if (action === "offers") {
      const { url, headers } = sb();
      const r = await fetch(`${url}/rest/v1/offers?select=id,amount_usd,email,created_at,stone_id,stones(name,images)&order=created_at.desc`, { headers });
      if (!r.ok) throw new Error(`db offers: ${r.status}`);
      const rows = await r.json();
      const offers = rows.map((o) => ({
        id: o.id, amount_usd: o.amount_usd, email: o.email, created_at: o.created_at,
        stone_id: o.stone_id, stone_name: o.stones?.name || o.stone_id,
        stone_original: o.stones?.images?.original || null,
      }));
      return res.json({ offers });
    }

    // ---- dream budget (admin) ----
    if (action === "budget") {
      const cfg = await budget.loadConfig();
      const usage = await budget.computeUsage(cfg);
      return res.json({ usage });
    }
    if (action === "budgetSet") {
      const { monthlyCapUsd, totalCapUsd, costPerDreamUsd } = req.body;
      await budget.setBudget({ monthlyCapUsd, totalCapUsd, costPerDreamUsd });
      return res.json({ usage: await budget.computeUsage() });
    }
    if (action === "budgetTopUp") {
      await budget.topUp({ scope: req.body.scope, amountUsd: req.body.amountUsd });
      return res.json({ usage: await budget.computeUsage() });
    }

    // ---- everything below needs the database ----
    if (!process.env.SUPABASE_URL || !process.env.SUPABASE_SERVICE_KEY) {
      res.statusCode = 500;
      return res.json({ error: "Storage is not configured." });
    }

    // ---- create (multi-photo, admin-chosen primary) ----
    if (action === "create") {
      const { name = "", width_cm, depth_cm, photos = [], primary = 0 } = req.body;
      if (!Array.isArray(photos) || photos.length < 1 || photos.length > MAX_PHOTOS) {
        res.statusCode = 400; return res.json({ error: `1 to ${MAX_PHOTOS} photos.` });
      }
      const ordered = photos.slice();
      const pi = Number(primary) || 0;
      if (pi > 0 && pi < ordered.length) { const [p] = ordered.splice(pi, 1); ordered.unshift(p); }
      const dims = [num(width_cm), num(depth_cm)];
      const id = (slug(name) || "stone") + "-" + Math.random().toString(36).slice(2, 6);
      const images = {};
      for (let i = 0; i < ordered.length; i++) {
        const buf = Buffer.from(String(ordered[i]), "base64");
        if (buf.length < 1000 || buf.length > 8_000_000) { res.statusCode = 400; return res.json({ error: `Photo ${i + 1} is empty or too large.` }); }
        const key = i === 0 ? "original" : "original_" + (i + 1);
        images[key] = await upload(`${id}/${key}.jpg`, buf);
      }
      const { url, headers } = sb();
      const r = await fetch(`${url}/rest/v1/stones`, {
        method: "POST",
        headers: { ...headers, "Content-Type": "application/json", Prefer: "return=minimal" },
        body: JSON.stringify({
          id, name: String(name).trim() || id, width_cm: dims[0], height_cm: null, depth_cm: dims[1],
          dimensions_approx: false, status: "processing", images,
        }),
      });
      if (!r.ok) throw new Error(`db insert: ${r.status} ${(await r.text()).slice(0, 200)}`);
      return res.json({ id, photos: ordered.length });
    }

    const stone = await row(String(req.body.id || ""));
    if (!stone) { res.statusCode = 404; return res.json({ error: "Unknown stone." }); }

    if (action === "analyze") return res.json(await stageAnalyze(stone));
    if (action === "look") return res.json(await stageLook(stone, Number(req.body.index) || 0));
    if (action === "cutout") return res.json(await stageCutout(stone));

    // ---- edit name / size ----
    if (action === "update") {
      const fields = {};
      if (typeof req.body.name === "string" && req.body.name.trim()) fields.name = req.body.name.trim();
      for (const k of ["width_cm", "height_cm", "depth_cm"]) {
        if (k in req.body) fields[k] = req.body[k] === null || req.body[k] === "" ? null : num(req.body[k]);
      }
      if (!Object.keys(fields).length) { res.statusCode = 400; return res.json({ error: "Nothing to update." }); }
      await patch(stone.id, fields);
      return res.json({ ok: true, id: stone.id });
    }

    if (action === "finalize") {
      const looks = Array.isArray(stone.images?.looks) ? stone.images.looks.filter((l) => l && l.src) : [];
      const legacy = KINDS.filter((k) => stone.images?.[k]).length;
      if (looks.length < 1 && legacy < 1) { res.statusCode = 400; return res.json({ error: "No looks generated yet." }); }
      await patch(stone.id, { status: "available" });
      if (process.env.RESEND_API_KEY && process.env.OFFER_NOTIFY) {
        const { stoneEmail, send } = require("./_email.js");
        const dims = [["width_cm", "wide"], ["height_cm", "tall"], ["depth_cm", "deep"]]
          .filter(([k]) => stone[k] > 0).map(([k, w]) => `${stone[k]} cm ${w}`).join(" · ");
        await send({
          resendKey: process.env.RESEND_API_KEY,
          to: process.env.OFFER_NOTIFY,
          subject: `${stone.name} is ready — live in the gallery`,
          html: stoneEmail({
            preheader: `${stone.name} finished processing and is live on stones.art.`,
            heading: `${stone.name} is ready`,
            intro: stone.character || "Processed, framed, and hanging in the gallery.",
            image: looks[0]?.src || stone.images?.original || null,
            rows: [
              { label: "Stone", value: stone.name },
              ...(dims ? [{ label: "Size", value: dims }] : []),
              { label: "Id", value: stone.id },
            ],
            cta: { label: "See it live", url: "https://stones.art" },
          }),
        }).catch((e) => console.error("ready email:", e.message));
      }
      return res.json({ ok: true, id: stone.id });
    }

    // ---- delete a stone (row + its R2 images + its dreams) ----
    if (action === "delete") {
      const { url, headers } = sb();
      // remove dependent dream rows first (they reference this stone)
      await fetch(`${url}/rest/v1/dreams?stone_id=eq.${encodeURIComponent(stone.id)}`, {
        method: "DELETE", headers: { ...headers, Prefer: "return=minimal" },
      }).catch(() => {});
      // delete the stone row
      const del = await fetch(`${url}/rest/v1/stones?id=eq.${encodeURIComponent(stone.id)}`, {
        method: "DELETE", headers: { ...headers, Prefer: "return=minimal" },
      });
      if (!del.ok) {
        const t = (await del.text()).toLowerCase();
        res.statusCode = del.status === 409 || t.includes("foreign key") ? 409 : 502;
        return res.json({
          error: del.status === 409 || t.includes("foreign key")
            ? "This stone has offers attached — those are kept, so the stone can't be auto-deleted. Tell me if you want to delete it with its offers."
            : `Delete failed (${del.status}).`,
        });
      }
      // best-effort: remove the stone's images from R2 (originals, looks, cutout)
      const img = stone.images || {};
      const urls = [];
      for (const k of Object.keys(img)) {
        if (k === "looks" && Array.isArray(img.looks)) img.looks.forEach((l) => l && l.src && urls.push(l.src));
        else if (typeof img[k] === "string") urls.push(img[k]);
      }
      const keys = urls.filter((u) => u && u.startsWith(CDN)).map((u) => u.slice(CDN.length + 1));
      await Promise.all(keys.map((k) => r2del(k).catch(() => {})));
      return res.json({ ok: true, id: stone.id, removedImages: keys.length });
    }

    res.statusCode = 400;
    return res.json({ error: "Unknown action." });
  } catch (e) {
    console.error("admin failed:", action, e.message);
    res.statusCode = 502;
    return res.json({ error: e.message });
  }
};
